name: flutter_ai_communications_workspace
publish_to: none

environment:
  sdk: ^3.13.1

workspace:
  - packages/flutter_ai_communications
  - packages/flutter_ai_communications_platform_interface
  - packages/flutter_ai_communications_shared
  - packages/flutter_ai_communications_ios
  - packages/flutter_ai_communications_android
  - packages/flutter_ai_communications_web
  - packages/flutter_ai_communications_macos
  - packages/flutter_ai_communications_windows
  - packages/flutter_ai_communications_linux
  - example

dev_dependencies:
  flutter_lints: ^6.0.0
