#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
RECEIPT_DIR="${RECEIPT_DIR:-/tmp/flutter_ai_communications_receipts}"
mkdir -p "$RECEIPT_DIR"
ENV_FILE="${RECEIPT_DIR}/interactive-ios-macos.env"
cd "$REPO_ROOT"

COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
ISSUES_BASE="https://github.com/JohnGalt1717/flutter_ai_communications/issues"
ROW_IDS=()

want_macos() { [[ "$RUN_SCOPE" == macos || "$RUN_SCOPE" == both ]]; }
want_ios()   { [[ "$RUN_SCOPE" == ios || "$RUN_SCOPE" == both ]]; }

sanitize() {
  printf '%s' "$1" | tr '\n' ' ' | tr -d '\r'
}

record_row() {
  local id="$1" issue="$2"
  local bash_id="${id//-/_}"
  local status_key="${bash_id}_STATUS" notes_key="${bash_id}_NOTES"
  say "Row ${id}  (issue #${issue})"
  ask "$status_key" "Result [pass / fail / skipped=capability / skipped=not-run]:"
  ask "$notes_key" "Notes (model + OS + accessory, or skip reason):"
  local status notes
  status="$(sanitize "${!status_key:-skipped=not-run}")"
  notes="$(sanitize "${!notes_key:-}")"
  [[ -z "$status" ]] && status="skipped=not-run"
  write_env "${id}_STATUS" "$status"
  write_env "${id}_NOTES" "$notes"
  write_env "${id}_ISSUE" "$issue"
  ROW_IDS+=("$id")
}

skip_row() {
  local id="$1" issue="$2" reason="$3"
  write_env "${id}_STATUS" "$reason"
  write_env "${id}_NOTES" "not in this run"
  write_env "${id}_ISSUE" "$issue"
  ROW_IDS+=("$id")
}

emit_receipt() {
  local json="${RECEIPT_DIR}/${COMMIT}-interactive-ios-macos.json"
  local md="${RECEIPT_DIR}/${COMMIT}-interactive-ios-macos.md"
  write_env ROW_IDS "${ROW_IDS[*]}"
  write_env COMMIT "$COMMIT"
  ENV_FILE="$ENV_FILE" RECEIPT_JSON="$json" RECEIPT_MD="$md" python3 - <<'PY'
import json, os, pathlib
from datetime import datetime, timezone

env_path = pathlib.Path(os.environ["ENV_FILE"])
data = {}
for line in env_path.read_text().splitlines():
    if not line or "=" not in line:
        continue
    key, _, value = line.partition("=")
    data[key] = value

row_ids = [r for r in data.get("ROW_IDS", "").split() if r]
rows = []
for rid in row_ids:
    rows.append({
        "id": rid,
        "issue": data.get(f"{rid}_ISSUE", ""),
        "status": data.get(f"{rid}_STATUS", "skipped=not-run"),
        "notes": data.get(f"{rid}_NOTES", ""),
    })

payload = {
    "commit": data.get("COMMIT", ""),
    "date": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "operator": data.get("OPERATOR", ""),
    "scope": data.get("RUN_SCOPE", ""),
    "macos_id": data.get("MACOS_ID", ""),
    "ios_id": data.get("IOS_ID", ""),
    "macos_os": data.get("MACOS_OS", ""),
    "ios_model_os": data.get("IOS_MODEL_OS", ""),
    "accessories": data.get("ACCESSORIES", ""),
    "issues": ["26", "92", "100", "93"],
    "rows": rows,
}
json_path = pathlib.Path(os.environ["RECEIPT_JSON"])
json_path.write_text(json.dumps(payload, indent=2) + "\n")

def issue_rows(num):
    return [r for r in rows if r["issue"] == str(num)]

def table(rs):
    lines = ["| Row | Result | Notes |", "| --- | --- | --- |"]
    for r in rs:
        notes = r["notes"].replace("|", "/")
        lines.append(f"| `{r['id']}` | {r['status']} | {notes} |")
    return "\n".join(lines) if rs else "_No rows in this run._"

md = []
md.append(f"# iOS/macOS interactive receipts (`{payload['commit']}`)")
md.append("")
md.append("Job: `.agents/workflows/interactive-ios-macos.md`")
md.append("")
md.append(f"- Operator: {payload['operator']}")
md.append(f"- Scope: {payload['scope']}")
md.append(f"- macOS: `{payload['macos_id']}` {payload['macos_os']}")
md.append(f"- iPhone: `{payload['ios_id']}` {payload['ios_model_os']}")
md.append(f"- Accessories: {payload['accessories']}")
md.append(f"- Receipt JSON: `{json_path}`")
md.append("")
md.append("## All rows")
md.append("")
md.append(table(rows))
md.append("")
for num, title in (("92", "#92 macOS #89 + iPhone #88"),
                   ("26", "#26 remaining physical iPhone / prove"),
                   ("100", "#100 Mac execution"),
                   ("93", "#93 iOS detach")):
    md.append(f"## {title}")
    md.append("")
    md.append(table(issue_rows(num)))
    md.append("")
pathlib.Path(os.environ["RECEIPT_MD"]).write_text("\n".join(md))
print(json_path)
print(os.environ["RECEIPT_MD"])
PY
}

RUN_SCOPE="${1:-}"
if [[ -z "$RUN_SCOPE" ]]; then
  printf '\n  Platforms: macos  |  ios  |  both\n'
  ask RUN_SCOPE "Platforms to run (macos / ios / both):"
fi
RUN_SCOPE="$(printf '%s' "$RUN_SCOPE" | tr '[:upper:]' '[:lower:]')"
case "$RUN_SCOPE" in
  macos|ios|both) ;;
  *) RUN_SCOPE="both" ;;
esac
write_env RUN_SCOPE "$RUN_SCOPE"

SETUP_STAGES=3
MACOS_STAGES=7
IOS_STAGES=12
CLOSE_STAGES=2
TOTAL_STAGES=$SETUP_STAGES
if want_macos; then TOTAL_STAGES=$((TOTAL_STAGES + MACOS_STAGES)); fi
if want_ios; then TOTAL_STAGES=$((TOTAL_STAGES + IOS_STAGES)); fi
TOTAL_STAGES=$((TOTAL_STAGES + CLOSE_STAGES))

banner "iOS/macOS interactive receipts"

# ── Setup ────────────────────────────────────────────────────────────────
stage "Devices"
say "The agent launches the example and taps Flutter keys."
say "You plug accessories, listen, and tap OS Allow / Isolation sheets."
note "Job: .agents/workflows/interactive-ios-macos.md"
note "Never uninstall the iOS example. Wireless iPhone is not USB handset proof."
open_url "${ISSUES_BASE}/92"
open_url "${ISSUES_BASE}/26"
open_url "${ISSUES_BASE}/100"
step "Look at flutter devices (id column)."
if command -v flutter >/dev/null 2>&1; then
  flutter devices || true
fi
ask MACOS_ID "macOS device id [macos]:"
ask IOS_ID "Physical iPhone id (USB preferred):"
[[ -z "$MACOS_ID" ]] && MACOS_ID="macos"
write_env MACOS_ID "$MACOS_ID"
write_env IOS_ID "$IOS_ID"
write_env COMMIT "$COMMIT"
note "commit ${COMMIT}"

stage "Accessories"
say "Capability-gated rows skip unless the hardware is here."
step "AirPods (or similar BT) for #89 / #88 / #26."
step "USB headphones or interface for mid-Session switch (optional)."
step "Brio-class webcam + USB render for unplug fallback (optional)."
step "CarPlay / generic BT only if you will sit in the car / pair them."
ask ACCESSORIES "Accessories on hand (comma list):"
write_env ACCESSORIES "$ACCESSORIES"

stage "Operator and OS"
ask OPERATOR "Your name or handle:"
ask MACOS_OS "This Mac model + macOS version:"
ask IOS_MODEL_OS "iPhone model + iOS version (or 'none'):"
write_env OPERATOR "$OPERATOR"
write_env MACOS_OS "$MACOS_OS"
write_env IOS_MODEL_OS "$IOS_MODEL_OS"

# ── macOS ────────────────────────────────────────────────────────────────
if want_macos; then
  stage "macOS — launch"
  say "Ask the agent to: cd example && flutter run -d ${MACOS_ID} --vm-service-port=50000"
  say "Then Agent Lens attach + flutter-skill inspect."
  step "If macOS asks for Microphone, Allow this app."
  pause "Press Enter when the example is up on this Mac."

  stage "macOS — pci built-in Pair (#100 C)"
  say "Idle or lobby. Built-in mic and speakers should share Pair id built-in."
  step "Tell the agent to screenshot Endpoints. Confirm one built-in Pair, not two pci strangers."
  record_row macos-pci-builtin 100

  stage "macOS — AirPods after start (#92 A2 / #89)"
  step "System Settings → Sound → Output: AirPods (or similar) as default."
  step "Agent taps lobby-enter, then lobby-join. Speak; watch capture-rms."
  step "Playback must stay on AirPods — not silently jump to Mac speakers."
  step "Desired = Applied = Observed on the AirPods Pair."
  record_row macos-airpods-start 92

  stage "macOS — mid-Session switch (#92 A2 / #89)"
  step "While the meeting Session is live, tap built-in or USB in Endpoints."
  step "Audio must stick on the new render after the engine rebind."
  record_row macos-mid-session-switch 92

  stage "macOS — USB+Brio unplug"
  if confirm "USB render + Brio-class capture are connected?"; then
    step "Idle: preference-editor. Chip Brio on the USB render row. pref-apply."
    step "lobby-enter. desired-render USB, desired-capture Brio, preference-controlled true."
    step "Unplug Brio. Render stays USB; capture walks to the next listed mic."
    record_row macos-unplug-brio 26
  else
    skip_row macos-unplug-brio 26 "skipped=capability"
    note "recorded skipped=capability"
  fi

  stage "macOS — prove (#26)"
  step "Agent taps prove on the meeting bar. echo-proof updates."
  note "This is host loopback identity, not analog speaker→mic native proof."
  record_row macos-prove 26

  stage "macOS — native 20-cycle (#26)"
  say "Ask the agent to stop flutter run, then:"
  note "cd example && flutter test integration_test/native_orchestration_test.dart -d ${MACOS_ID}"
  step "nativeFailuresSkipped must be false. Copy the receipt path."
  record_row macos-native-20 26
fi

# ── iPhone ───────────────────────────────────────────────────────────────
if want_ios; then
  stage "iPhone — launch"
  warn "Never uninstall the iOS example. flutter run over the existing install."
  warn "Simulator is not this job. Wireless is not USB speaker/handset proof."
  say "Ask the agent to: cd example && flutter run -d ${IOS_ID} --vm-service-port=50001"
  step "First start(): tap Allow on the phone. Keep the flutter run process."
  pause "Press Enter when the example is up on the iPhone."

  stage "iPhone — idle catalog (#92 A3 / #88)"
  step "Do not Join yet. Connect AirPods (CarPlay if you are in a car)."
  step "Agent inspects Endpoints. AirPods / CarPlay must appear."
  note "A2DP-only accessories are render-only; that is expected after #88."
  record_row ios-idle-catalog 92

  stage "iPhone — speakerphone ↔ handset (#26)"
  step "USB physical iPhone. Agent Join, then tap speakerphone, then handset."
  step "You listen: loudspeaker vs earpiece. Both directions work."
  step "Desired = Applied = Observed on each pick."
  record_row ios-speaker-handset 26

  stage "iPhone — AirPods before Session (#26)"
  step "AirPods connected. Agent lobby-leave if needed, then enter + join."
  step "Both capture and render on AirPods. You hear playback in the buds."
  record_row ios-airpods-before 26

  stage "iPhone — AirPods during Session (#26)"
  step "Stay in the meeting. Disconnect AirPods → speakerphone, still duplex."
  step "Reconnect → AirPods both sides. Capture stream must not be replaced."
  record_row ios-airpods-during 26

  stage "iPhone — live catalog refresh (#92 A3 / #88)"
  step "Stay in the meeting. Agent scrolls/refreshes Endpoints."
  step "Playback must not stop. Session stays. You still hear the fixture/agent."
  record_row ios-live-catalog-refresh 92

  stage "iPhone — Explicit selection (#26)"
  step "Agent taps endpoint-<renderId> (speaker or handset)."
  step "preference-controlled becomes false. Observed converges. You hear that render."
  record_row ios-explicit 26

  stage "iPhone — interruption (#26)"
  step "Trigger a phone call or Siri, then return to the app."
  step "Session pauses or interrupts; resume keeps the same Session object."
  record_row ios-interruption 26

  stage "iPhone — Isolation Open (#26)"
  step "Agent taps open-isolation. You handle the system Isolation UI."
  step "Decline still leaves the Session ready (raised floor is OK)."
  record_row ios-isolation 26

  stage "iPhone — prove (#26)"
  step "Agent taps prove. echo-proof updates."
  note "Host loopback identity — not analog native proof."
  record_row ios-prove 26

  stage "iPhone — detach (#93)"
  step "Catalog observation on (idle Endpoints visible). Agent Lens hot restart."
  step "After idle returns, there must be no leftover playAndRecord voice session."
  record_row ios-detach 93

  stage "iPhone — native 20-cycle (#26)"
  say "USB iPhone only. Ask the agent to stop flutter run, then:"
  note "cd example && flutter test integration_test/native_orchestration_test.dart -d ${IOS_ID}"
  if confirm "CarPlay or extra generic BT available to log as capability rows?"; then
    record_row ios-carplay 26
    record_row ios-generic-bt 26
  else
    skip_row ios-carplay 26 "skipped=capability"
    skip_row ios-generic-bt 26 "skipped=capability"
  fi
  record_row ios-native-20 26
fi

# ── Close ────────────────────────────────────────────────────────────────
stage "Write receipt"
emit_receipt
RECEIPT_JSON="${RECEIPT_DIR}/${COMMIT}-interactive-ios-macos.json"
RECEIPT_MD="${RECEIPT_DIR}/${COMMIT}-interactive-ios-macos.md"
note "JSON ${RECEIPT_JSON}"
note "Markdown ${RECEIPT_MD}"
if [[ -f "$RECEIPT_MD" ]]; then
  printf '\n'
  cat "$RECEIPT_MD"
fi
pause "Press Enter after you have copied any fail notes."

stage "Comment GitHub issues"
say "Comments belong on #92 (A2/A3), #26 (remaining iPhone), #100 (Mac pass), #93 (detach)."
say "Close a ticket only when every required box is pass or accepted skipped=capability."
if confirm "Post the markdown receipt as comments via gh now?"; then
  if command -v gh >/dev/null 2>&1; then
    body="$(cat "$RECEIPT_MD")"
    gh issue comment 92 --body "$body" || SKIPPED+=("gh comment #92")
    gh issue comment 26 --body "$body" || SKIPPED+=("gh comment #26")
    gh issue comment 100 --body "$body" || SKIPPED+=("gh comment #100")
    gh issue comment 93 --body "$body" || SKIPPED+=("gh comment #93")
  else
    SKIPPED+=("gh not on PATH — paste ${RECEIPT_MD} onto the issues")
  fi
else
  note "Paste ${RECEIPT_MD} onto the issues when the agent agrees the rows are final."
fi

finish
